---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: cms1
  domain: foo.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: “web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true”
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-09026704
  image_type: t2.micro
  image_id: ami-0be2743b
  security_groups:
  - default
  - web_tools
  external_host: ec2-54-191-147-191.us-west-2.compute.amazonaws.com
  external_ip: 54.191.147.191
  internal_host: ip-172-31-30-146.us-west-2.compute.internal
  internal_ip: 172.31.30.146
  zone: us-west-2a
  provider: aws
  platform: linux
  root_device_type: ebs
  static_ip: 54.191.147.191
- volumes: {}
  static_ips:
    cms1: 54.191.147.191
